### ISSUE TITLE
Error P2025 missing from docs

### ISSUE THREAD

**Issue by scriptcoded** [prisma/web#1321]
## Problem

The docs are missing the `Record to update not found.` error code `P2025`.

https://www.prisma.io/docs/reference/api-reference/error-reference#prismaclientknownrequesterror

## Suggested solution

Add the `P2025` code to the docs

## Alternatives

Remove the error from Prisma? No I'm sorry, I don't have a good alternative.

## Additional context

:)

**Comment by mhwelander** [comment]
Added - thanks for raising!

**Comment by BenjaminGuzman** [comment]
Hi, I was working with Prisma and making some unit testing and expected an update to fail, I checked the docs to see which error would Prisma throw and didn't find one, so I just ran the test and the error code was `P2025`.

The [documentation](https://github.com/prisma/docs/blob/05483756b337a53d679fce85630906cfc549bd8e/content/400-reference/200-api-reference/075-error-reference.mdx) (commit [38a849e](https://github.com/prisma/docs/commit/38a849e56ef60a1ed6803fe9605d39852a1096e8)) says `P2025: "Record to delete does not exist."`

So I searched in GitHub and found this issue. I don't know why it was changed, but I did another test to delete a non existing record in the database and the error code was the same `P2025`.

I didn't make a pull request 'cause I don't know why it was changed after this issue was closed, maybe it was for a good reason

**Comment by janpio** [comment]
Error P2025 is listed on https://www.prisma.io/docs/reference/api-reference/error-reference#prisma-client-query-engine, bottom of the table. Is it missing somewhere else?

**Comment by BenjaminGuzman** [comment]
Yes, but the description is `P2025: "Record to delete does not exist."`, even though the error is thrown when the record to **delete or update** does not exist. So I think maybe just a little update to the documentation like `P2025: "Record to update or delete does not exist."` would be nice.

**Comment by janpio** [comment]
Ah, is the same message thrown not matter if you delete or update? Or does the actual error message include both cases? (The table of error messages is generated based on the code and should not need to be adapted manually - in theory...)

**Comment by BenjaminGuzman** [comment]
Yes, the same error code `P2025` is thrown no matter if it is an update or delete, however the message is different.

```
try {
    prisma.entity.delete({
	    where: {
		    id: incorrectId
    	    }
    });
} catch(e) {
    console.log(e.code); // P2025
    console.log(e.message); // An operation failed because it depends on one or more records that were required but not found. Record to delete does not exist.
}
```
and

```

try {
    prisma.entity.update({
	    where: {
		    id: incorrectId
    	    },
           data: newData
    });
} catch(e) {
    console.log(e.code); // P2025
    // however
    console.log(e.message); // An operation failed because it depends on one or more records that were required but not found. Record to update not found.
}
```

But the docs say `P2025` is thrown when the `Record to delete does not exist.`

**Comment by Nith567** [comment]
So i got the error i developed a function when we press button then in the prisma database gets update then i got this same error, can you give me the solution for this
