### ISSUE TITLE
Postgres domain via prisma migrate

### ISSUE THREAD

**Issue by chrissisura** [prisma/web#1554]
Hey guys, 

since the GA of prisma migrate I would really like to switch our entire project to migrate instead of introspecting. One thing I couldn't figure out out how to do via migrate is creating a postgres domain.

Example use cases would be storing only valid email or phone
```
CREATE DOMAIN "PhoneType" AS citext CHECK (VALUE ~ '^\+?[0-9]{7,30}$');
```
Is that possible somehow?

Best regards and thanks for be awesome!

**Comment by chrissisura** [comment]
Also trigger would be amazing. Even though middleware is sounds nice in theory, it is limited in a lot of ways such as nested calls from some other models not triggering the middleware and so on. Would be great to have triggers to our disposal for some advanced database logic and sanity checks. Cheers

**Comment by tomhoule** [comment]
Hi @chrissisura ! 

The prisma schema language is not complete and there is no syntax for domains, check constraints or triggers. However, migrate is designed with escape hatches so you can still express that.

- For domains, what _should_ work is creating the domain in your SQL migration with the DDL statement you mentioned in the issue description, then using the `Unsupported(...)` type in your Prisma schema. For example:

```prisma
model User {
  id Int @id
  userPhoneType Unsupported("PhoneType")
}
```

The only problem with this is that the field will be ignored in your prisma client API, because the client doesn't know how to handle this. A feature request issue on the prisma/prisma repo would be welcome for visibility :)

- For triggers, you should be able to edit the SQL migrations generated by migrate to add them manually (or create an empty migration and add them there), and it should work. If not, we consider this a bug and if you open an issue, we'll work on it. Also there, if you have ideas about a more convenient syntax in the prisma schema, an issue would be great so we have a space to discuss this.

I hope it helps, don't hesitate if you have other questions :)

**Comment by chrissisura** [comment]
Awesome thank you!

**Comment by ankur-arch** [comment]
Hey @chrissisura  👋 thanks for opening this issue! I'm aware that it has been around for a while but we're only now getting to a major cleanup of the docs repo, so apologies for the delay. I'm closing this issue as it seems to be outdated, but please feel free to open other issues in the future if you notice anything that can be improved in the Prisma docs 🙏.
