### ISSUE TITLE
Document connection lifetime

### ISSUE THREAD

**Issue by Sytten** [prisma/web#1657]
A few releases ago we added `max_connection_lifetime` (default `None`) and `max_idle_connection_lifetime` (default `5m`) to the engine. Those should be documented.

**Comment by janpio** [comment]
Hold: We are not ready to document these features yet.

**Comment by rpbarnes** [comment]
are y'all going to document these? Is it possible to set a `max_connection_lifetime`? Does it default to `5m`? I searched the docs and can't find anything for `max_connection_lifetime`.

**Comment by SSabev** [comment]
> Hold: We are not ready to document these features yet.

So, what can we do to recycle connections in the meantime then?

**Comment by xoapit** [comment]
Any updates?

**Comment by ankur-arch** [comment]
Using a `pool_timeoout` should be enough to [recycle connections](https://www.prisma.io/docs/orm/overview/databases/postgresql#arguments).

**Comment by TristanMenzinger** [comment]
@ankur-arch I can't confirm this works I'm afraid. We use RLS on sessions, and these are not kept alive (or restored) even if `pool_timeout` is set to 0 (or a high value). Imho, `max_idle_connection_lifetime` should be documented since it is a relevant information for all developers using any connection- or session-level configuration (via RLS for example).

For anyone developing on serverless, `max_idle_connection_lifetime` should be set to a very high value / the serverless function's timeout, since they'll likely also use `connection_limit=1`?
