### ISSUE TITLE
Extend enableCustomId for heading anchors to work with TOC and Subsections

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#1765]
https://prisma-company.slack.com/archives/C5Z9TH6N9/p1622050642068500

can we influence the anchor naming of headlines?
https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference/#-modifier would be neat as https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference/#square-brackets-modifier instead

Yes and no - the feature is enabled in gatsby-remark-autolink-headers but the feature is not accounted for in our TOC (which I think is custom) or our <Subsections /> component, which means doing this:
`## Reasons to use the <inlinecode>Json</inlinecode> field type {#something-dark-side}`
Adds {#something-dark-side} to the TOC text.

**Comment by nilubava** [comment]
@meletj @nikolasburk Is this feature still relevant/useful?

Context: The `enableCustomId` option is not compatible with our current version of `gatsby-plugin-mdx` as the syntax is invalid in MDX v2. We need to create a custom plugin using [rehype-slug-custom-id](https://github.com/unicorn-utterances/rehype-slug-custom-id) instead. So it would be great to know if this is a useful feature for our near future. If not, I would prefer not to spend time on this since we may change docs architecture soon(ish).

**Comment by janpio** [comment]
From my side: Yes, some of the auto generated anchors are bad and being able to customize them would be very helpful.

**Comment by jharrell** [comment]
Headings are customizable in Docusaurus: https://docusaurus.io/docs/3.5.2/markdown-features/toc#heading-ids
