### ISSUE TITLE
Technology switcher state should be reflected in URL path and meta information (title, description, ...)

### ISSUE THREAD

**Issue by schickling** [prisma/web#180]
To improve SEO and shareability of the docs pages using a technology switcher should reflect its state in the URL and meta information (title, description, ...).

**Comment by nikolasburk** [comment]
I just discussed the SEO effects with Joel, it seems like it would generally better to have the db and lang be reflected in the URL path and not its URL params. 

In my understanding, the problem is that Google doesn't crawl URL params by default, so we need to configure that in the Google Search Console to do so explicitly. The drawback with this is that this only is for Google search, other search engines might ignore the params.

I did configure the Search Console for now: 

![image](https://user-images.githubusercontent.com/4058327/79468615-6d939d00-7fff-11ea-9f35-af1e24e2f261.png)

I think we should keep this issue open to eventually get back to it and make it the tech choices part of the URL. As of now, this is fairly low prio though.

**Comment by schickling** [comment]
Seems like the meta information is not updated statically. I suggest to make this at least a short-mid term priority.

![image](https://user-images.githubusercontent.com/1567498/79471786-548ceb00-8003-11ea-9c06-f75d5e78d59e.png)

**Comment by nikolasburk** [comment]
I think Nilu is currently already looking into that. We're exploring different ways to make it happen since we need to include the meta data for the different technologies in the same frontmatter.

**Comment by nilubava** [comment]
@schickling The seo issue will be solved in https://github.com/prisma/prisma2-docs/pull/241/files.
