### ISSUE TITLE
Setting up Prisma in a hoisted environment (pnpm, npm workspaces)

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#1910]
Internal context: https://prisma-company.slack.com/archives/C5Z9TH6N9/p1624327195329300

**Comment by millsp** [comment]
For some more context, here's how to set up a project with pnpm https://github.com/millsp/prisma-pnpm-workspace. There are two important things:
* [Generation](https://github.com/millsp/prisma-pnpm-workspace/blob/8b02b3f3bf57c04987d3c1d9a42f87e2f8395c88/app1/prisma/schema.prisma#L11)
  This ensures that the client is generated in the sub-project's `node_modules` folder. Otherwise it would get generated in the root / hoisted `node_modules` (for both `app1` & `app2`) and two clients could overwrite each other.  
* [Imports](https://github.com/millsp/prisma-pnpm-workspace/blob/8b02b3f3bf57c04987d3c1d9a42f87e2f8395c88/app1/index.ts#L1)
  Because `@prisma/client` is hoisted in the root folder and reused by `app1` & `app2` (symlinked in their respective `node_modules`), we cannot resolve types or any nearby generated client. Thus it has to be imported this way.
 
The main purpose of this doc is to help users that would like to generate more than one client while working in a hoisted environment (in this case, a `pnpm` workspace).

**Comment by janpio** [comment]
Meaning: If you use pnpm or similar, and just have 1 generated Client, you can do what exactly?

**Comment by molebox** [comment]
This should be added to the Development environment section

**Comment by jharrell** [comment]
@millsp is this still the case?

**Comment by millsp** [comment]
Yes this is something a lot of people who use multi-service monorepos actually run into. It's not obvious why the Prisma Clietn package gets deduplicated by some package managers, that in turn makes that you cannot output/generate multiple clients. There's one thing that I would change from my example though: the custom output into node modules, I'd just make it a custom output in the project folder and use a gitignore not to include the files.

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
