### ISSUE TITLE
[docs] Dead links

### ISSUE THREAD

**Issue by benmccann** [prisma/web#243]
The text "Prisma Client API reference." on https://www.prisma.io/docs/understand-prisma/introduction results in a 404

**Comment by nainardev** [comment]
Works now

**Comment by benmccann** [comment]
Really? I'm not sure it does. The link for "Prisma Client API reference." on https://www.prisma.io/docs/understand-prisma/introduction still results in a 404 for me

**Comment by ghost** [comment]
The docs are still WIP. See https://github.com/prisma/prisma2-docs/issues/126

**Comment by miller-productions** [comment]
I've just cloned the docs repo and it is working fine locally in dev. There is a noticable difference however.

Locally, in dev, the URLs look like this...

`http://localhost:8000/understand-prisma/introduction`

Whereas on the live site in production, the URLs look like this...

`https://www.prisma.io/docs/understand-prisma/introduction`

Note the inclusion of `/docs/` in the path.

In the source, links are specified as relative paths as such...

_For example, this is a link from content/02-understand-prisma/01-introduction.mdx_

`[Prisma schema file](../../reference/tools-and-interfaces/prisma-schema/prisma-schema-file)`

Perhaps the config needs to be tweaked ever so slightly so that the URL is the same in dev and prod.

_Apologies, I wasn't able to check what a build looked like locally since `yarn build` failed for me out of the box... `"gatsby-plugin-algolia" threw an error while running the onPostBuild lifecycle`. It was looking for something related to Algolia, the error returned was ` AlgoliaSearchError: Please provide an application ID. Usage: algoliasearch(applicationID, apiKey, opts)`_

**Comment by mhwelander** [comment]
Thank you very much for taking the time to investigate! 🙏 I've run a link checker on the entire site and fixed all broken links; we're also in the process of improving our link checker.
