### ISSUE TITLE
Searching is sluggish

### ISSUE THREAD

**Issue by janpio** [prisma/web#370]
Using the search field is pretty sluggish right now, it takes quite some time until my typed characters appear.

**Comment by pantharshit00** [comment]
We have `500ms` debounce in the search which I feel is unnecessary. 

This PR introduced it as extra perf measure: https://github.com/prisma/docs/pull/201

The real problem at that time was that we were creating algolia instance on each render which the PR fixed. 

We should try removing the debounce and see how the perf is. Otherwise there will always be a 500ms delay.

**Comment by matthewmueller** [comment]
This is happening to me too: https://www.loom.com/share/e930278497a143b7abc7a28ab328b0cf

It's really hard to use right now. It doesn't appear to be debouncing at all.
