### ISSUE TITLE
Better docs for VS Code (and Jetbrains IDE) setup

### ISSUE THREAD

**Issue by nikolasburk** [prisma/web#386]
We should improve the "Editor setup" docs and add more docs about VS Code and also about the Jetbrains plugins created by our community.

**Comment by janpio** [comment]
\+ Sublimetext

**Comment by ltlian** [comment]
I am a VS Code user and have been exploring the prisma.vscode-graphql extension the past couple of days, and eventually came here to create a similar issue.

My first impression was very positive, but for now I found it too time consuming trying to configure it fully partly due to my difficulty in finding appropriate documentation.

The links regarding watchman and graphql-config under the [Usage](https://github.com/prisma-labs/vscode-graphql#usage)-section in the github readme could use some attention, as the former is 404 and the latter ultimately leads you to https://graphql-config.com/introduction which mentions files other than the concrete `.graphqlconfig` expected by the extension.

edit: I only just now realized prisma and prisma-labs are two different orgs, each with their own vscode repo 🤦‍♂️ I can take my feedback there.

**Comment by janpio** [comment]
@ltlian Indeed, @nikolasburk' issue here only refers to https://github.com/prisma/vscode which is the main VSCode extension for Prisma 2.

I will hide both your and my comment now as "Offtopic".

**Comment by pantharshit00** [comment]
+Vim :D 

We even have language server properly working there

**Comment by mhwelander** [comment]
https://www.prisma.io/docs/concepts/more/editor-setup
