### ISSUE TITLE
Document how to locally install the databases we support

### ISSUE THREAD

**Issue by matthewmueller** [prisma/web#457]
**Why?**

You should be using the same database for development as in production. Sometimes this is not feasible, but for the databases we currently support, it's fortunately very easy to setup. We just need to guide our users how.

**For example**

|Database|Mac|Windows|Linux|
|:-|:-|:-|:-|
| Postgres| `brew install postgres`|todo|todo|
| MySQL| `brew install mysql`|todo|todo|

**Additional Notes**

- We may need to provide instructions on how to install brew or some installable .dmg if available
- I think we should also optionally provide a way to run these database as a service so they bootup on start. In homebrew that's easy `brew services start postgres`.

**Comment by janpio** [comment]
I think this would actually be a good thing not to document in our docs, but for example on How to data and "just" link to there from the docs.

**Comment by mhwelander** [comment]
/cc @imchairmanm - shall we move this? Package managers:

* Chocolatey
* Homebrew
* Eventually WPM https://devblogs.microsoft.com/commandline/windows-package-manager-preview (Windows)

**Comment by imchairmanm** [comment]
In terms of moving the content, I have the PostgreSQL installation guides ported (pretty much as-is) to How to Data.  You can see them [here](https://dataguide.netlify.app/postgresql/setting-up-a-local-postgresql-database/).

The MySQL and SQLite ones haven't been ported yet because I haven't worked on those paths yet.  We can see if it'd make sense to port those earlier than planned if it's important to get those out of the doc right now.  I'm just a bit hesitant to add more sections with only a single article in each of them to the HtD project right now.  Curious what others think.

As for the package managers, I initially didn't include them for macOS and Windows because of time restraints.  If I recall though, there were some questions as to recommending them, because:

* They sometimes weren't among of the installation methods recommended by the project
* They sometimes do their own bespoke service and configuration file management, which increases the if-else branches we have to do in other documents.
* In some cases, it was difficult to establish who was actually managing the packages within the package manager.  I think it'd be fine if the package is managed by either the database project's team or the package manager's team, but in some cases I don't think I was able to establish that.  This is more of a problem with Chocolatey than Homebrew, if I recall.
* In the case of Chocolatey, there's also the concern Jan brought up about just lack of ubiquity.  Although they're catching up, most Windows users just don't seem to be on the package manager train yet, so it feels odd to tell them to invest in a package manager ecosystem for the sake of a single package.  We can get around this one by just not worrying about it though :).

That being said, brew is super popular and should maybe be included in spite of those problems.  I'm more on the fence about Chocolatey, though I've heard people who use it think it's fine.

**Comment by mhwelander** [comment]
Closing as not part of doc site, and Data Guide now has installation guides for all 3 dbs.
