### ISSUE TITLE
GitHub Action: Check for broken links

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#483]
> (How it would work: Github workflow that just runs that part of the build script, red x when it fails and green checkmark if it is happy)

Full thread: https://prisma-company.slack.com/archives/C5Z9TH6N9/p1592476676060100

**Comment by rahul3v** [comment]
Can I see the Full thread if possible

**Comment by janpio** [comment]
Unfortunately not (as people did not expect this to become public), but I can paraphrase:

- We have a build step that outputs warnings in the Netlify console about broken links:
![image](https://user-images.githubusercontent.com/183673/85197110-3d0dff00-b2df-11ea-88cf-5c35b6ec6b12.png)
- This issue is about the idea to turn that into a Github action that produces a check on all PRs that would fail if there are broken links, and pass if there are not.
- The script or build step can probably be extracted and modified to not only warn, but fail on errors.
- That of course also requires the codebase to be really broken link free when we start.

Does that give you enough context to understand what we meant?

**Comment by rahul3v** [comment]
That will be enough @janpio, No problem at all, Well what I understand if we fix the warning of broken links, I think we can fix this
and I already did that on my local deployment, Just waiting for some response from @mhwelander to confirm about  non-linking of few warning links in #485, then I will make pull request with the fix.

**Comment by mhwelander** [comment]
Removed some of the `<a id="test"></a>` anchor links for now and used a nearby heading (needs must) - feature request #508 here. There are 0 now (ignore Netlify - there's an issue: #506)

Big thanks @rahul3v for all the work you've put into the link checker 🚀

**Comment by janpio** [comment]
But we do not have an action that runs automatically and fails PRs via GH Action yet, right?

**Comment by nilubava** [comment]
Closing this since we do not have a Github Action for broken links but rather a plugin which outputs the broken links as errors during the build process.
