### ISSUE TITLE
queryRaw and executeRaw not available

### ISSUE THREAD

**Issue by JamesForan** [prisma/web#537]
I am using the PrismaClient, and going through the examples, but the methods queryRaw and executeRaw are not available. I can only see raw..

I am not sure if this is an issue with the documentation, or the build.

**Comment by mhwelander** [comment]
Hi! `queryRaw` and `executeRaw` should exist, since `2.0.0-beta.8`. Some things to try (do pardon me if you've already tried this):

* Check that you've upgraded `@prisma/client` as well as `@prisma/cli`
* Also make sure you re-generated your Prisma Client with `npx prisma generate`
* If you upgraded `@prisma/cli` or `@prisma/client` recently, try restarting the TS server (ctrl/command+shift+p in a `.ts` file, choose TypeScript: Restart TS server

**Comment by JamesForan** [comment]
Hi Martina,

Thanks for your reply. I am working the the example repo "[deployment-example-netlify"](https://github.com/prisma/deployment-example-netlify) and this had an old version in the package.json file ran an npm upgrade and now I have it!

Thanks,
