### ISSUE TITLE
We could give some numbers for connection pool size / concurrency limits for Serverless AWS Lambda or link to GitHub issue

### ISSUE THREAD

**Issue by Jolg42** [prisma/web#667]
To me my default thinking was that Lambda only have 1 CPU, looking on Google says that sometimes they have 2 but real testing below says it's always 2 so it could be nice to have a reference to that in the docs section for users:

| Memory (MB) | CPU (Cores) | Default Pool Size (`= 2 * CPU + 1`) |
| :---------: | :---------: | --------------------------- |
|     128     |      2      | 5                           |
|     256     |      2      | 5                           |
|     512     |      2      | 5                           |
|    1024     |      2      | 5                           |
|    2048     |      2      | 5                           |
|    3008     |      2      | 5                           |

So now I just changed the memory setting, but the reported cpu value is always the same, meaning we'll give 2 IO threads per lambda and 5 connections.

And to be clear. This is what we see from the OS layer. It might be wrong, it might be less or more. But the system sees 2 and will act based on that.

_Originally posted by @pimeys in https://github.com/prisma/prisma/issues/942#issuecomment-558153490_

Different popular PostgreSQL instances and their limits:

| Instance Size | used_at_start | max_conn | res_for_super | res_for_normal |
| :-----------: | :---------------------: | :---------------------: | :---------------------: | :--------------------: |
|   t2.micro    | 7 |            87          | 3                         | 77                       |
|   t2.small    | 7 |           198        | 3                         | 188 |
| t2.medium | 7 | 413 | 3 | 403 |
| t2.large | 7 | 856 | 3 | 846 |
| t2.xlarge | 7 | 1743 | 3 | 1733 |
| t2.2xlarge | 7 | 3518 | 3 | 3508 |
| m5.large  | 7 | 823 | 3 | 813 |
| m5.xlarge | 7 | 1691 | 3 | 1681 |
| m5.2xlarge | 7 | 3429 | 3 | 3419 |
| m5.4xlarge | 7 | 5000 | 3 | 4990 |

Some of the connections are used already when the instance is running, so I'd base my calculations for the connections reserved for normal users (the last column).

So with the default pool size of five connections:
Lambda Concurrency Limit based on Different popular PostgreSQL instances
| Instance Size | Lambda Concurrency Limit |
| :-----------: | :---------------------: |
| t2.micro | 15 |
| t2.small | 37 |
| t2.medium | 80 |
| t2.large | 169 |
| t2.xlarge | 346 |
| t2.2xlarge | 701 |
| m5.large | 162 |
| m5.xlarge | 336 |
| m5.2xlarge | 683 |
| m5.4xlarge | 998 |

_Originally posted by @pimeys in https://github.com/prisma/prisma/issues/942#issuecomment-558269427_

**Comment by mhwelander** [comment]
Note to Martina: Request details

**Comment by mhwelander** [comment]
@Jolg42 Salutations - could you tell me a bit more about when a user might want this information? Is it something I would mention in the [deployment docs](https://www.prisma.io/docs/concepts/components/prisma-client/deployment/#database-connection-limit)?

Does it change this sentence?

> Serverless (FaaS): It's recommended to **set the connection limit to 1** if you're not using an external connection pooler because each incoming request starts a short-

And what does "Lambda Concurrency Limit based on Different popular PostgreSQL instances" affect?

**Comment by Jolg42** [comment]
Note: we have pgbouncer docs that also help around connection management.

This "Lambda Concurrency Limit based on Different popular PostgreSQL instances" means that for a PostgreSQL RDS instance size for example t2.micro you can only have 15 lambda concurrent lambda running. After that limit you risk having lambdas trying to connect with the db but all the connections would be taken for the PostgreSQL db (busy).

It's relevant in an AWS deployment guide/doc.

**Comment by mhwelander** [comment]
Pardon my n00b-ness here - but is this right?

1. I'm a lambda function that processes analytics data (website visits) - I'm very busy, so there are 20 instances of me working pretty much constantly 
2. I have 2 CPUs, which means my connection pool size is 5 - and all my friends' connection pool size is also 5 - this means we have 5 connections available to read/write to the database. BUT.. we're lambdas, we only use 1 connection and then disconnect, so you really should set the connection limit to 1 if you're not using a something like pgBouncer to queue connections.
3. All 20 of us try to connect to a t2.micro - that isn't going to work, because t2.micro has a 15 lambda limit. If you didn't set the connection limit to 1, only 3 of us can connect (3 * pool size of 5)

**Reasons people need to know lambdas having 2 CPUs:** just FYI - you're creating a pool with 5 connections instead of 3 (unless you explicitly set the connection limit to 1) 
**Reason people need to know about lambda concurrency limits:** another FYI - you're going to run out of connections faster than you think unless you use pgBouncer or set connection limit to 1

**Comment by Jolg42** [comment]
3. `because t2.micro has a 15 lambda limit.` actually a more accurate fact ([posted by @pimeys here](https://github.com/prisma/prisma/issues/942#issuecomment-558269427) and I just added it to the description of the issue as well) is that the max number of connections for t2.micro is 77.
(15 lambda * 5 (default pool size) = 75 connections, so we're potentially at the limit in this default case)

@pimeys could you review maybe? I'm not 100% sure of the pool behavior setting when it's set to 1 🤔

**Comment by mhwelander** [comment]
Added link to this in doc.
