### ISSUE TITLE
Document `DateTime` formats

### ISSUE THREAD

**Issue by nikolasburk** [prisma/web#668]
Right now, we only mention `DateTime` as an available type in [docs](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-schema/models#scalar-fields-vs-relation-fields), but we don't give specific examples about the format of this type. We should give some examples and explain the format that's accepted.

![image](https://user-images.githubusercontent.com/4058327/87649612-cedb2180-c750-11ea-9486-d6aeb29597ec.png)

**Comment by mhwelander** [comment]
I had this issue myself yesterday. I'm thinking a separate 'Working with DateTime', since it's quite a special type.

**Comment by janpio** [comment]
Issues we receive about problems people are having with or without timezones etc confirm the need for this.

**Comment by heymartinadams** [comment]
Totally. Also, on a related note, did a search in the docs for `DateTime` CRUD ops, and couldn’t find anything. https://github.com/prisma/prisma-client-js/issues/419 was helpful.

**Comment by carchrae** [comment]
i just floundered through this.  the lack of support for `date` (vs `datetime` aka `timestamp`) seems to be an unfortunate limitation of prisma at the moment.  you can pass strings, but since prisma doesn't seem to handle a date-only string, like `2021-03-29`, you need to pass it an ISO string and pretend you want a timestamp instead.

eg,    (btw, `date` is my column name)
```js
where: {
  date: '2021-03-29T00:00:00.000Z'
}
```

this worked for both a column of type timestamp and date.  i tested on both types (postgres 12, prisma 2.19)

so, in my code, to query by date (not including the time), i needed to generate a string using this code

```js
where: {
  date : moment.utc(dateString).toISOString()
}
```

or if you don't have moment on hand, 
```js
where: {
  date : dateString + 'T00:00:00.000Z'
}
```



or if you wanted to search for all times on a particular date, you need to do something like this  (as mentioned in https://github.com/prisma/docs/issues/668#issuecomment-661370488).  

```js
where: {
  date : {
     gte: moment.utc(date).toISOString(),
     lt: moment.utc(date).add(1,'day').toISOString()
  }
}
```


and absolutely, there are a lot of gotchas regrading time zones (and both your server config and db config).  the above presume utc (which is the most sane default)

**Comment by carchrae** [comment]
related issue: https://github.com/prisma/prisma/issues/4355#issuecomment-737914647

**Comment by janpio** [comment]
Please make sure your investigation above is also mentioned in an issue in the main repository @carchrae - or even in a new issue there. We are aware of limitations with dates and might be looking into fixing these in the future - so every comment and issue that explains what exactly and why this is limiting will influence our decision making there. (Issues here though tend to be overlooked for obv reasons)

**Comment by mhwelander** [comment]
Related: #548 #812

**Comment by heymartinadams** [comment]
Not to throw another wrench in the plans... https://2ality.com/2021/06/temporal-api.html

**Comment by janpio** [comment]
If that happens, we are _more_ than happy to adopt it and update our APIs. But history tells us, that is still quite some time out before you can rely on it and we only support Node versions that do as well.

**Comment by nikolasburk** [comment]
Two tasks:
- add to `DateTime` in reference
- add "Working with `DateTime` to: https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields
