### ISSUE TITLE
Wrong preview loaded and wrong title shown for docs URLs

### ISSUE THREAD

**Issue by nikolasburk** [prisma/web#673]
I think I have seen this a few times already but here's a concrete example. If you post this link on social media (e.g. Twitter/Slack): https://www.prisma.io/docs/reference/database-connectors/mysql#type-mapping-between-mysql-to-prisma-schema 

You get this preview:

![image](https://user-images.githubusercontent.com/4058327/87765016-905c6a00-c817-11ea-99bf-261e75c7c6ab.png)

So somehow the meta tags don't seem to be applied properly since the docs page has the rights ones: https://github.com/prisma/docs/blob/master/content/03-reference/02-database-connectors/04-mysql.mdx

**Comment by janpio** [comment]
The meta tags match the actual page title:
![image](https://user-images.githubusercontent.com/183673/87824366-69cd1c00-c875-11ea-82c4-136e3f5aea70.png)

The source of the page on the other hand does not include that string and title at all: https://raw.githubusercontent.com/prisma/docs/master/content/03-reference/02-database-connectors/04-mysql.mdx

**Comment by 2color** [comment]
For clarity, this problem was with pages that shared the same last section of the path, e.g., `https://www.prisma.io/docs/guides/database-workflows/import-and-export-data/postgresql`, `https://www.prisma.io/docs/guides/database-workflows/unique-constraints-and-indexes/postgresql`, and `https://www.prisma.io/docs/concepts/database-connectors/postgresql`.

I found the cause of the problem; a PR should follow shortly.
