### ISSUE TITLE
Test updatedAt and now() in different regions

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#787]
## Context 

(See Jan's comment) Find out what date/time gets written to the database if your db is in a different region.

## Suggested action

Update reference docs for that attribute and function.

**Comment by janpio** [comment]
To set and inform expectations:
- updatedAt = Prisma functionality
- @default(now()) = database functionality

**Comment by nikolasburk** [comment]
@janpio We do have docs that state that `default(now())` is DB-level but `@updatedAt` is Prisma-level. Do you think we need more information than that? If so, what specficically?

**Comment by janpio** [comment]
The underlying problem here is that if you have your app and your database in different regions/timezones, `updatedAt` and `now()` could lead to different values. As this can be highly confusing, I assume we thought back then that we experimentally confirm this and then add a note to this at appropriate spots.
