### ISSUE TITLE
(Redirects) Migrating database setup and data import/export docs to Data Guide

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#788]
Context: https://prisma-company.slack.com/archives/C5Z9TH6N9/p1598256445103200

Creating task and assigning to you so that we can keep track! :)

**Comment by imchairmanm** [comment]
@mhwelander Just to clarify based on the conversation in Slack, we want to migrate the database set up guides and the data import / export guides, correct?  The data validation guides were going to stay in the docs for now, right?  I'm just asking because the issue title mentions validation.

Can you confirm that the guides in these sections are the ones that need to be migrated over to the Data Guide:

* https://www.prisma.io/docs/guides/database-workflows/setting-up-a-database
* https://www.prisma.io/docs/guides/database-workflows/import-and-export-data

Thanks!

**Comment by mhwelander** [comment]
That's correct - database set-up and import/export can move completely, and data validation should stay. I made a mistake with the title - sorry!

**Comment by imchairmanm** [comment]
Okay, cool! Thanks!

**Comment by imchairmanm** [comment]
Okay, so these guides are all now in the Data Guide:

* [Setting up a local PostgreSQL database](https://dataguide.prisma.io/postgresql/setting-up-a-local-postgresql-database)
* [Setting up a local MySQL database](https://dataguide.prisma.io/mysql/setting-up-a-local-mysql-database)
* [Setting up a local SQLite database](https://dataguide.prisma.io/sqlite/setting-up-a-local-sqlite-database)

* [Importing and exporting data in PostgreSQL](https://dataguide.prisma.io/postgresql/inserting-and-modifying-data/importing-and-exporting-data-in-postgresql)
* [Importing and exporting data in MySQL](https://dataguide.prisma.io/mysql/importing-and-exporting-data-in-mysql)
* [Importing and exporting data in SQLite](https://dataguide.prisma.io/sqlite/importing-and-exporting-data-in-sqlite)

@mhwelander I don't really know how to do the redirects we require, so if I can get some help with that, we can remove the pages from the docs and redirect to the equivalent data guide pages.
