### ISSUE TITLE
Environment variables reference

### ISSUE THREAD

**Issue by do4gr** [prisma/web#809]
I can think of custom binaries and logging / debugging levels. There might be more that I am not aware of.

**Comment by mhwelander** [comment]
Sounds like a good candidate for an API ref page. 👍

**Comment by mhwelander** [comment]
* New page in the 'Reference' section on the same level as CLI docs
* Suggest using headings rather than a table as we've had some issues with indexing table rows + makes search results nicer if we use headings (jump straight to env variable)
* Available env variables scattered around the docs - suggest searching 'environment variables' as a starting point, then ask in e.g. prisma2 channel if there's a list / if anything is missing
* Short description and example for each env var
* Suggest adding links to reference docs for first instance of a variable on the pages where they appear (we're just using `<span class="api"></span>` for the label at the moment: 

![image](https://user-images.githubusercontent.com/849648/111142338-dc1d0a00-8584-11eb-9870-9339d6a01f35.png)

**Comment by Jolg42** [comment]
Page is here https://www.prisma.io/docs/reference/api-reference/environment-variables-reference
