### ISSUE TITLE
Feedback: Spacing in left-hand nav

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#892]
If I create items directly under the main section heading, there needs to be a little bit of space underneath the list of items:

![image](https://user-images.githubusercontent.com/849648/95304854-7dd95600-0885-11eb-8d95-b8dee6426f9d.png)

**Comment by mhwelander** [comment]
Related: #637

**Comment by hrescak** [comment]
@mhwelander I *think* this is something that can be resolved with folder structure - as far as I understand it a folder in content always creates a `<ul>` so it gives it a bit more space below, but the **getting started** is not in a folder so instead of the item being in `li > ul > li` it's only `li` which makes it not have the bottom margin that comes from the list.

**Comment by hrescak** [comment]
I think there's a way we can specify this with CSS

**Comment by mhwelander** [comment]
Moving this to backlog as I ended up restructuring Getting Started
