### ISSUE TITLE
Feedback: long content right-side navigation not scrollable

### ISSUE THREAD

**Issue by thebiglabasky** [prisma/web#895]
Looking at [this section](https://deploy-preview-878--prisma2-docs.netlify.app/api-ref/prisma-schema/prisma-schema-reference) you can see that there are more sub-sections available but you can't scroll them, making the "Content" side navigation not fully usable.
You need to scroll all the way down to be able to see the bottom of it.

Top or middle of the page: can't see below `@@updatedAt`
![image](https://user-images.githubusercontent.com/431257/95308566-5d5fca80-088a-11eb-9fd1-9c72aa533aab.png)

Bottom: can see the rest
![image](https://user-images.githubusercontent.com/431257/95308503-4b7e2780-088a-11eb-8934-38c7647d5be4.png)

**Comment by hrescak** [comment]
@nilubava  This should probably behave the same way the left sidebar does - in any event, we should try for it not to have a persistent scrollbar

**Comment by mhwelander** [comment]
@nilubava @hrescak Is this in progress still? It does not behave like the left-hand scrollbar at the moment.

I also wonder if we could have the right-hand nav 'follow' you as you scroll, so that if you're looking at a heading named 'generators', that is also what's highlighted in the right-hand nav? rather just scrolling with the length of the page (for API reference in particular you'll hit the end of the nav long before you hit the end of the page)

Example: https://doc.sitecore.com/developers/100/sitecore-experience-platform/en/sitecore-cortex-processing-engine.html (scroll and see right-hand nav)

**Comment by hrescak** [comment]
Let's make it move as the left one and @mhwelander will create an issue for the super awesome behavior

**Comment by mhwelander** [comment]
Closing this as it's implemented in the branch.
