### ISSUE TITLE
Feedback: Getting started's "Set up Prisma" section layout feels odd

### ISSUE THREAD

**Issue by thebiglabasky** [prisma/web#896]
Despite the spacing mentioned [here](https://github.com/prisma/docs/issues/892), I find that "Set up Prisma" a bit strange since the sub-sections are not indented, yet the title has a 15 mins pill next to it.
![image](https://user-images.githubusercontent.com/431257/95308902-c21b2500-088a-11eb-82ef-720241457698.png)

I wonder if that would be supposed to either be slightly indented so we understand the relation, or if there's a need for a foldable behavior as for other subsections (e.g. 
![image](https://user-images.githubusercontent.com/431257/95308995-dd863000-088a-11eb-82f5-6c48d9700ebc.png))

**Comment by hrescak** [comment]
Proper spacing above the Set Up Prisma header should fix the hierarchy here. We'll also move 15m to all of the pages despite the duplication. It might be worth re-visiting the timings there because it's likely SQL vs prisma migrate set ups take different amounts of time (I'd assume migrate is faster)
