### ISSUE TITLE
OS tabs should be in sync 

### ISSUE THREAD

**Issue by divyenduz** [prisma/web#953]
Example: https://www.prisma.io/docs/understand-prisma/under-the-hood#prisma-engines

On this URL, switching to windows on one tab should switch to windows for all the tabs. Usually, a user is looking at docs for a specific OS.

**Comment by ankur-arch** [comment]
Closing due to being outdated.

**Comment by KaKi87** [comment]
Hi,

The issue is still relevant : https://www.prisma.io/docs/v6/orm/more/internals/engines

<img width="253" height="554" alt="Image" src="https://github.com/user-attachments/assets/5f503d2f-8199-4e41-ae5c-ec168ae679a0" />

And it's also relevant for DBMS selection : https://www.prisma.io/docs/orm/prisma-client/special-fields-and-types/working-with-json-fields

<img width="217" height="580" alt="Image" src="https://github.com/user-attachments/assets/9819073a-49eb-4d5f-9f34-d0a8fbf8d49f" />

Thanks
